schema_version = "1.0.0"

id = "custom_autosave"
version = "1.6.0"
name = "Custom Autosave"
tagline = "Customizable autosave functionality with unsaved file option"
maintainer = "SlaneDRV <slane.drv@gmail.com>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

tags = ["System"]

[permissions]
files = "Save files to temporary location"